### ISSUE TITLE
Éviter les doublons

### ISSUE THREAD

**Issue by lolavlmt** [Sebp06/Peyardsebastien_2_17022021#1]
https://github.com/Sebp06/Peyardsebastien_2_17022021/blob/3e84de1d605c5b87f7450c9e8ee627b1e17a0290/index.html#L31

Quelle est la raison pour laquelle tu as écrit deux fois "Hébergements" (l'un dans un `<div>`, et l'autre dans un `<a>`) ?
Que cherches-tu à faire exactement ?

A ton avis, pourquoi faut-il éviter ces doublons ?

**Comment by Sebp06** [comment]
J'ai pas voulu faire de doublon c'est juste que j'ai voulu faire une ancre mais si je supprime le div l'ancre ne vas plus fonctionner

**Comment by Sebp06** [comment]
c'est bon j'ai compris merci Lola je pensai que tu parler de supprimer la div j'avais pas bien compris plutôt
