### ISSUE TITLE
Utilisation de "for" sur les labels

### ISSUE THREAD

**Issue by lolavlmt** [Sebp06/Peyardsebastien_2_17022021#2]
https://github.com/Sebp06/Peyardsebastien_2_17022021/blob/3e84de1d605c5b87f7450c9e8ee627b1e17a0290/index.html#L48

Pourquoi est-il important d'indiquer un attribut "for" sur les `<label>` ?

**Comment by Sebp06** [comment]
C'est important car c'est pour lier le label au champ
